apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: quay.io/argoprojlabs/argocd-e2e-container:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret-volume
          mountPath: "/secrets"
          readOnly: true
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: guestbook-ui-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: guestbook-ui-secret
              key: password
      volumes:
      - name: secret-volume
        secret:
          secretName: guestbook-ui-secret
          defaultMode: 0400
