apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: guestbook-ui-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    ENusername: AgAn2aW6eF2RVNKyydLeIAUysYxZ6fB3muhl7QYWer+7OWeY2ZK1eCkiOlufLg+g4+Az4SAKHnRHuQRQKVSzOLhJjObIR4Ybn7nHZ+BBlHgRmpkXPIlkI0A4n25qyhg0Gue5penQ2yD711aAlW1asQTnjtwgst52GXcHQupNOx/8P0PzlD9AxeclHw8McLdIRqNmBkgc75N04Yl8jQDXuGifO+9gxf2n0ABbMoFCjC0BF5s0C/tKsK0IHQISHpEabVN0PDaob7c+vGV1tdMNt2ZFunVPS98TtIR6+/KFY5MMdJdC4b8xtp48tq6F3onHPdySg9FuQ0iPXiW2reGi4cPuv5goYsI3F1U89QuCEFkMdXnODmFsSQIdfBDYLVO+GQUXYA+9AZGRLvh+tTSmL2v0cYr9doHx4GNBlUIFbSg9FedBoFiAgGBCWdkJnBxjMKXU8jbHRfhDxA9cKepn4pXJoeTwtVXWj4zrEjEKU1c23Efq7ncUT/ipy2JxhbK4RA4el2PCSoYqgGF1rPHc84s5BWxq1r9ptIDR6WWfkU0qwsXgHU3njnyk72ojz4DLXhFKPA6oearVf8mqWU07vdIeigI0Jt6KEQuV4IxjgHZ03u/tY5IboeEwx3dq9JmB9FrU2IHeXnH8/5tQWmgOEs1jgF44vq15IomRZXNLfdNl3IRuu4lT2ftlpm9ngYidJl4ImiuA/4eO
  template:
    metadata:
      name: guestbook-ui-secret
    type: Opaque
    data:
      username: '{{ index . "ENusername" }}'
