apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: guestbook-ui-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    ENusername: AgArm21nd94W2N2papP2HHv/+v+RqSbXq/P81uA3QePEtrJ5Zy4RpB07UQK6/RAIlX63udAQohutDXnbXGPHCWA4HudCWnTvBiFH3VN/MAhAl0Dss8hpQMgQYJPZpV8CxsY+xWryVzKy6eSUP2VIFygA+JkRoro9+2+9jF1NYjjKkZUXAFQYtlWmXA9WNVGB2ej0xinWWDms3bN9n1zewB2/c/++kvDHEo8K2dTsDqD/j5gGcOcwP/7P4hqogOkyP9jv/n/b/cL8nArSSNH3gJcDcHgduV2KrQygBObdPSNW85NqUM3OinDA9UR5JWEiF1DcnM3weE+W9lvpV3I8YiHQst2T17U2gaRMGA3zdzOWemcYWihbxOH0hfIF+D3R9W8OhifjYCPNqG05XEkAvZO8M1EiuuDcpg6B1f8T+V3fuDCV+o683klSOma5Ym3zcNitgTDI6W6mSM0mVEnuwatwV3L8VPA0HnNTxrQhNfbrbcTGyR/cc9kHZ+Rjvow3ofHcKraRMwtOUUPPHsml8LSGGJ96rEqeR22qZmREUmEspfwwn0Dw/gdabyZc+fAUYMlRNpX3ecHBdjm9/GMXGRdNYFFxvuULCh6u36cg/xMjd2lhX1VjhtrdzX35fyR2uye9KT8DtghMEzzs2VFcMR1vTQT+qTRKrcVp6/ShODhRanpYZmsDHnSMgIjuY+/Vm1hEO4gAhurpWepWHw==
  template:
    metadata:
      name: guestbook-ui-secret
    type: Opaque
    data:
      username: '{{ index . "ENusername" }}'
