apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: guestbook-ui-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    ENusername: AgCib0bctH+Cwjw/xOjmXSHBtPLBSYaFSGZNzQiF6EjaSts2dCIlTaar1ecxp71x16FV3k/1eYsyRsaJlTC9QmkweiTDGRCey5y/a6qIVP02yjqu3UTvOBX0QgXkVK9Twnbc4UTcKuhbviv1leHaaY+o0TsAIMtW9nNSjoVZXALPnwNuSK99zNN4eUkAQEZYATROggJycCRqA51lF/+fXMTJ95ah1cRJG+43ahay9p7U/RiMqTfxFZPW7DalR5z/Z0aM4mn2uD1pPQTwMcPFnr4jo5wmTU+vGfyAmc4dOzN7PLn26gn1c8abqEK2SWvTCWoPASanx7rqKuMwJV5CMr2RPd0mZJy9faFpqWckpqOs8Ft8Mql0f8DqTZCrHXHzl30xWUSrwISh7KO8/eCxmPKd51JWxasbkjVIK9fmFRT64hustKPQXNUT0oAKV366GfwpiQUe2JXVqRvhhAdQTXl5O05zeaEp8WTpsECfBlIkuikuX5Xq9LMoVnwIA50pe4XN6otEvYa1qVsDOZTZh3DJlMEe7XTKr6JQYPhGn2k0pBEYKH10wtjlaYm5qESCegq1Ha//ZJDWxev5UoTfb43+VSt2AG/sp34chR7ionRBgbKKNxszPPnGbRh2a6tQIqwRD4zNA42Pc4Rd2u8nwx2rRkuU6is6h7Qx7Z+zjwUdz3LiVyEMsBlVakiu2JlwxWhaoMzGpha5
  template:
    metadata:
      name: guestbook-ui-secret
    type: Opaque
    data:
      username: '{{ index . "ENusername" }}'
